---

- name: (configurate) | check systemctl
  shell: /usr/bin/which systemctl
  register: systemctl_exist
  ignore_errors: yes


- name: (configurate) | enable elasticsearch
  shell: /bin/systemctl daemon-reload && /bin/systemctl enable elasticsearch.service
  when: systemctl_exist.rc == 0


- name: (configurate) | update-rc.d elasticsearch
  shell: /usr/sbin/update-rc.d elasticsearch defaults
  when: systemctl_exist.rc != 0


- name: (configurate) | change mode and owner for directories
  shell: chown -R {{item}}:{{item}} /var/lib/{{item}}
  with_items:
    - elasticsearch


- name: (configurate) | replace elasticsearch config file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml


- name: (configurate) | restart elasticsearch
  service:
    name: elasticsearch
    state: restarted

